title: AOM SQL
description: Spletna stran namenjena pisanju o prigodah na nivoju SQL Server.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jkeskuel.github.io" # the base hostname & protocol for your site
remote_theme: pages-themes/tactile@v0.2.0


# Build settings
markdown: kramdown

# Author settings
author:
  name: Jure Kranjc
  email: jure.kranjc@aom.si

# Social links
social:
  linkedin: jkeskuel
  github: jkeskuel

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme